export const LOGIN_USER = 'LOGIN_USER';
export const IS_LOGGING_IN_USER_ERROR = 'IS_LOGGING_IN_USER_ERROR';

export const SIGNUP_USER = 'SIGNUP_USER';
export const IS_SIGNING_UP_USER_ERROR = 'IS_SIGNING_UP_USER_ERROR';

export const IS_LOADING ='IS_LOADING';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_CART_LENGTH = 'GET_CART_LENGTH';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';

