import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import ReduxProvider from "@/provider/reduxProvider";
import AuthProvider from "@/provider/authProvider";
import { checkAuthentication, getSession } from "@/utils/helpers";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const session = await getSession();

  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
          <Toaster/>
          <ReduxProvider>
            <AuthProvider session={session}>
              {session?.user && <Header />}
              {children}
              {session?.user && <Footer />}
            </AuthProvider>
          </ReduxProvider>

      </body>
    </html>
  );
};

export default RootLayout;
